import json,re
from pathlib import Path
root=Path(__file__).resolve().parents[2]
records=[]; strings=[]
def text(key,ko,en,args=0): strings.append([key,ko,en,args])
legacy={0:('STR_Lifesteal','광폭','Bloodlust','{0:0.#}초 동안 검 피해의 {1:0%}를 회복합니다.','For {0:0.#}s, sword hits heal for {1:0%} of damage.','DurationSeconds,LifestealRatio'),
1:('AGI_Poison','독 바르기','Venom Blade','{0:0.#}초 동안 검에 독을 바릅니다. 최대 {1:0}중첩, 중첩당 초당 {2:0.#} 피해, {3:0.#}초 지속.','Coat your sword for {0:0.#}s. Up to {1:0} stacks, {2:0.#} damage per stack per second for {3:0.#}s.','DurationSeconds,PoisonMaxStacks,PoisonDamagePerStackPerSecond,PoisonStackDurationSeconds'),
2:('CON_Kick','발차기','Kick','공격력의 {0:0%} 피해와 {1:0.#}m 밀치기. {2:0.#}초 동안 적을 느리게 합니다.','Deal {0:0%} attack damage and knock back {1:0.#}m. Slow the target for {2:0.#}s.','KickDamageMultiplier,KickKnockbackDistance,KickSlowDurationSeconds'),
3:('DEF_Taunt','도발','Taunt','다음 검 적중 시 {0:0.#}초간 적을 끌어들입니다. 받는 피해 감소와 반사 강화가 적용됩니다.','Your next sword hit forces the enemy toward you for {0:0.#}s and grants damage reduction and stronger reflection.','TauntDurationSeconds'),
10:('TACT_Dash','대시','Dash','전방으로 {3:0.##}초 동안 {0:0.#}m 대시합니다. 최대 {1:0}회 충전, {2:0.#}초마다 1회 회복.','Dash {0:0.#}m forward in {3:0.##}s. Stores {1:0} charges; recovers one every {2:0.#}s.','RollDistance,MaxCharges,CooldownSeconds,RollDurationSeconds'),
11:('TACT_Preset','프리셋 전환','Reconfigure','저장한 능력치 배분으로 전환하고 주 능력치에 맞는 보너스를 받습니다. 다시 사용하면 원래 배분으로 돌아갑니다.','Switch to your saved stat preset and gain a bonus based on its primary stat. Use again to return.',''),
20:('POLY_Roll','구르기','Roll','전방으로 {3:0.##}초 동안 {0:0.#}m 구릅니다. 최대 {1:0}회 충전, {2:0.#}초마다 1회 회복.','Roll {0:0.#}m forward in {3:0.##}s. Stores {1:0} charges; recovers one every {2:0.#}s.','RollDistance,MaxCharges,CooldownSeconds,RollDurationSeconds'),
21:('POLY_Preset','프리셋 전환 (미사용)','Reconfigure (unused)','이전 데이터 호환용 스킬입니다. 장착할 수 없습니다.','Legacy compatibility skill. Cannot be equipped.',''),
22:('POLY_Weapon','무기 스왑','Weapon Swap','검과 활을 교체합니다. {0:0.#}초 동안 이동 속도가 증가하고 다음 공격이 강화됩니다. 좌클릭을 길게 눌러 활을 충전합니다.','Swap between sword and bow. Gain movement speed for {0:0.#}s and empower your next hit. Hold attack to draw the bow.','WeaponSwapMoveBonusDurationSeconds')}
for path in sorted((root/'Assets/Player/skill').rglob('*.asset')):
 s=path.read_text(encoding='utf-8-sig'); kind=int(re.search(r'^  _skillKind: (\d+)',s,re.M)[1])
 if kind not in legacy: continue
 info=legacy[kind]
 params={m[1][0].upper()+m[1][1:]:float(m[2]) for m in re.finditer(r'^  _(\w+): (-?\d+(?:\.\d+)?)\s*$',s,re.M)}
 timing=[params.pop(k) for k in ['CastSeconds','DurationSeconds','CooldownSeconds']]
 prefixes={0:('Lifesteal',),1:('Poison',),2:('Kick',),3:('Taunt',),10:('Roll',),20:('Roll',),11:('Strategist','MaxHealthIncrease','Shield'),21:('Strategist','MaxHealthIncrease','Shield'),22:('MinimumBow','MaximumBow','Bow','WeaponSwap')}[kind]
 params={k:v for k,v in params.items() if k=='InputLockSeconds' or k.startswith(prefixes)}
 if kind in (10,20): params['MaxCharges']=2; params['RollDistance']=3.6
 if kind in (11,21):
  preset=s.split('  _targetPreset:')[1].split('  _maxHealthIncrease')[0]
  for stat in ['STR','CON','AGI','DEF']:
   match=re.search(r'    '+stat+r':\s*\n      Invested: ([\d.]+)',preset)
   params['TargetPreset'+stat]=float(match[1]) if match else 0
 records.append(dict(id=info[0],kind=kind,cast=timing[0],duration=timing[1],cooldown=timing[2],params=params,args=info[5],source='기존 에셋 유지; 프리셋 0은 기본 배분 사용',enabled=kind!=21))
 text(info[0]+'_Name',info[1],info[2]); text(info[0]+'_Desc',info[3],info[4],len(info[5].split(',')) if info[5] else 0)
def add(kind,id,name,en,cast,duration,cooldown,params,ko,eng,args,source='사용자 지정; 미지정 값은 초기 밸런스'):
 records.append(dict(id=id,kind=kind,cast=cast,duration=duration,cooldown=cooldown,params=params,args=args,source=source,enabled=True))
 text(id+'_Name',name,en); text(id+'_Desc',ko,eng,len(args.split(',')) if args else 0)
add(100,'STR_Hook','갈고리','Grappling Hook',.25,0,15,dict(Range=4,ProjectileSpeed=12,PullSpeed=8,Radius=.08,StopDistance=1),'사거리 {0:0.#}m. 갈고리에 직접 맞은 적을 앞으로 끌어옵니다. 던지고 회수하는 동안 이동·공격할 수 없습니다.','Range {0:0.#}m. Pull a directly hit enemy toward you. Movement and attacks are locked until the hook resolves.','Range')
add(101,'STR_WarCry','힘찬 함성','Rallying Cry',.7,10,25,dict(MoveMultiplier=1.2,IncomingMultiplier=.8),'{0:0.#}초 동안 이동 속도가 기본의 {1:0%}, 받는 피해가 {2:0%}가 됩니다.','For {0:0.#}s, movement speed becomes {1:0%} and incoming damage becomes {2:0%} of normal.','DurationSeconds,MoveMultiplier,IncomingMultiplier')
add(102,'SHARED_Charge','돌진','Charge',0,4,20,dict(AccelerationSeconds=2.5,InitialSpeedMultiplier=.8,MaximumAgiMultiplier=1.3,TurnDegreesPerSecond=60,DamageMultiplier=1,StunSeconds=1),'최대 {0:0.#}초 돌진. 걷기 속도의 {3:0%}로 출발, {1:0.#}초 후 AGI 몰빵 기본 속도의 {4:0%} 도달. 적마다 피해·{2:0.#}초 기절. 적중 후 계속 돌진. 점프·공격·스킬 키로 종료.','Charge up to {0:0.#}s. Start at {3:0%} walk speed; reach {4:0%} base AGI-specialist speed in {1:0.#}s. Damage and stun each enemy once for {2:0.#}s without stopping. Jump, attack or a skill key ends charge.','DurationSeconds,AccelerationSeconds,StunSeconds,InitialSpeedMultiplier,MaximumAgiMultiplier')
add(103,'AGI_Stealth','은신','Stealth',.3,0,20,dict(BreakDistance=1,BonusSeconds=3,AttackMultiplier=1.2),'모습을 숨깁니다. 공격·피격 또는 누적 {0:0.#}m 이동 시 해제됩니다. 해제 후 {1:0.#}초간 공격력이 기본의 {2:0%}가 됩니다.','Become invisible. Attacking, taking damage, or moving a total of {0:0.#}m breaks stealth and grants {2:0%} attack power for {1:0.#}s.','BreakDistance,BonusSeconds,AttackMultiplier')
add(104,'AGI_Knife','나이프 투척','Throwing Knives',.15,0,0,dict(MaxCharges=3,RechargeSeconds=8,DamageMultiplier=.5,Range=10,ProjectileSpeed=16,Radius=.06,ThrowInterval=.3),'키를 눌러 준비하고 좌클릭으로 투척합니다. 최대 {0:0}개, {1:0.#}초마다 1개 충전. 공격력의 {2:0%} 피해와 독 1중첩. 다시 스킬 키를 누르면 준비를 취소합니다.','Press the skill key to ready, then attack to throw. Holds {0:0} knives; recharges one every {1:0.#}s. Deals {2:0%} attack damage and adds one poison stack. Press the skill key again to cancel.','MaxCharges,RechargeSeconds,DamageMultiplier')
add(105,'CON_Berserk','광전사','Berserk',.4,0,20,dict(HealthDrainRatio=.03,MoveMultiplier=1.2,AttackSpeedMultiplier=1.3,AttackMultiplier=2,RecoveryRegenMultiplier=.5),'켜짐/꺼짐. 매초 최대 체력 {0:0%} 소모. 부족하면 체력 1을 남기고 종료. 이동 {1:0%}, 공속 {2:0%}, 공격력 {3:0%}. 재생 불가. 종료 후 {4:0.#}초간 쿨타임·재생 절반.','Toggle. Drain {0:0%} max HP/s; stop at 1 HP. Movement {1:0%}, attack speed {2:0%}, attack power {3:0%}. No regeneration. On ending: {4:0.#}s cooldown and half regeneration.','HealthDrainRatio,MoveMultiplier,AttackSpeedMultiplier,AttackMultiplier,CooldownSeconds')
add(106,'CON_Recovery','체력 가속','Vital Surge',.45,10,40,dict(HealthCostRatio=.3,HealRatio=.2,RegenMultiplier=2),'최대 체력의 {0:0%}를 즉시 소모하고 {1:0.#}초에 걸쳐 {2:0%}를 회복합니다. 그동안 체력 재생은 {3:0%}. 소모량보다 체력이 많아야 합니다.','Spend {0:0%} max health to restore {2:0%} over {1:0.#}s. Regeneration becomes {3:0%} during the effect. Requires health above the cost.','HealthCostRatio,DurationSeconds,HealRatio,RegenMultiplier')
add(107,'DEF_Bash','후리기','Crushing Blow',0,30,10,dict(StunSeconds=3,IncomingMultiplier=2),'다음 공격 적중 시 {0:0.#}초간 이동·공격을 막고, 해당 시간에 적이 받는 피해를 {1:0%}로 만듭니다. 준비 상태는 {2:0.#}초 유지됩니다.','Your next hit stuns for {0:0.#}s and makes the target take {1:0%} damage during the stun. The ready effect lasts {2:0.#}s.','StunSeconds,IncomingMultiplier,DurationSeconds')
add(108,'DEF_Thorns','가시','Thorns',0,10,25,dict(ReflectMultiplier=2),'{0:0.#}초 동안 반사 피해가 {1:0%}가 됩니다.','For {0:0.#}s, reflected damage becomes {1:0%}.','DurationSeconds,ReflectMultiplier')
add(109,'DEF_Fortify','굳히기','Fortify',.25,3,20,dict(DefenseMultiplier=2),'{0:0.#}초 동안 이동할 수 없고 방어력이 {1:0%}가 됩니다. 공격과 시점 전환은 가능합니다.','For {0:0.#}s, movement is locked and defense becomes {1:0%}. You can still attack and look around.','DurationSeconds,DefenseMultiplier')
add(110,'SHARED_Trap','덫 깔기','Trap',1.1,0,25,dict(Lifetime=60,MaxHealthDamageRatio=.2,RootSeconds=5,PlaceDistance=1.2,MaxCharges=3),'최대 {4:0}회 충전, {5:0.#}초마다 1회 회복. 스킬 키로 앞을 조준, 클릭으로 {3:0.#}초간 설치. {0:0.#}초 유지. 적 최대 체력 {1:0%} 피해·{2:0.#}초 이동/방향 봉쇄.','Stores {4:0} charges; recovers one every {5:0.#}s. Skill key previews; click to place in {3:0.#}s. Lasts {0:0.#}s; deals {1:0%} max HP and locks movement/turning for {2:0.#}s.','Lifetime,MaxHealthDamageRatio,RootSeconds,CastSeconds,MaxCharges,CooldownSeconds')
add(111,'TACT_Dice','주사위','Loaded Fate',.3,15,15,dict(Face1=-.3,Face2=-.2,Face3=-.1,Face4=.1,Face5=.2,Face6=.3),'{0:0.#}초간 모든 능력치 변경. 1~3: {1:0%}/{2:0%}/{3:0%}, 4~6: +{4:0%}/+{5:0%}/+{6:0%}. 사용 직후 쿨타임 시작.','Change all stats for {0:0.#}s. 1–3: {1:0%}/{2:0%}/{3:0%}; 4–6: +{4:0%}/+{5:0%}/+{6:0%}. Cooldown starts immediately.','DurationSeconds,Face1,Face2,Face3,Face4,Face5,Face6')
add(112,'POLY_Steal','스틸','Skill Steal',.25,0,20,dict(Range=4),'바라보는 {0:0.#}m 이내 적의 장착 스킬 하나를 복제합니다. 같은 키로 복제한 스킬을 1회 사용한 뒤 {1:0.#}초 쿨타임이 시작됩니다. 스틸 자체는 복제하지 않습니다.','Copy one equipped skill from the enemy you aim at within {0:0.#}m. Use it once with the same key, then begin a {1:0.#}s cooldown. Cannot copy Steal itself.','Range,CooldownSeconds')
jobs=[('STR','힘 특화','Strength Specialist','STR에 30 포인트 투자','Invest 30 points in STR','강력한 근접 공격과 추격으로 적을 압박합니다.','Pressure enemies with heavy melee attacks and pursuit.',[0,100,101,102]),('CON','체력 특화','Vitality Specialist','CON에 30 포인트 투자','Invest 30 points in CON','체력을 소모하거나 회복하며 오래 싸웁니다.','Spend and recover health to sustain a fight.',[2,105,102,106]),('AGI','민첩 특화','Agility Specialist','AGI에 30 포인트 투자','Invest 30 points in AGI','빠른 공격과 독, 은신으로 기회를 만듭니다.','Create openings with speed, poison, and stealth.',[1,103,104]),('DEF','방어 특화','Defense Specialist','DEF에 30 포인트 투자','Invest 30 points in DEF','공격을 버티고 반격하며 적을 제압합니다.','Withstand attacks, retaliate, and control enemies.',[3,107,108,109]),('TACT','전략가','Tactician','최대·최소 투자 차이 8 이상, 몰빵 제외','Investment spread of at least 8; not a single-stat build','대시, 프리셋, 덫과 주사위를 조합합니다.','Combine dashes, presets, traps, and fate.',[10,11,110,111]),('POLY','팔방미인','Polymath','최대·최소 투자 차이 7 이하','Investment spread of at most 7','무기 전환과 회피, 덫과 복제로 대응합니다.','Adapt with weapon swaps, evasion, traps, and copied skills.',[20,22,110,112])]
for i,j in enumerate(jobs):
 for suffix,ko,en in [('Name',j[1],j[2]),('Requirement',j[3],j[4]),('Desc',j[5],j[6])]: text('JOB_'+j[0]+'_'+suffix,ko,en)
for key,ko,en in [('Title','직업과 스킬','Jobs and Skills'),('Hint','직업마다 서로 다른 스킬 2개를 장착합니다.','Equip two different skills for each job.'),('Close','닫기','Close'),('Save','적용','Apply'),('Saved','장착 구성을 적용했습니다.','Loadout applied.'),('BattleLocked','전투 중에는 장착 스킬을 변경할 수 없습니다.','Skills cannot be changed during battle.'),('Slot1','1번 장착','Equip slot 1'),('Slot2','2번 장착','Equip slot 2'),('Current','현재 직업','Current job'),('Duplicate','같은 스킬을 두 슬롯에 넣을 수 없습니다.','The two slots must contain different skills.'),('Footer','Esc 닫기 · 장착 구성은 계정별로 이 기기에 저장됩니다.','Esc to close. Loadouts are saved per account on this device.')]: text('UI_Skill_'+key,ko,en)
text('UI_DiceResult','주사위 {0}  ·  모든 능력치 {1}{2}%','Dice {0}  ·  All stats {1}{2}%',3)
text('UI_SkillTiming','시전 {0:0.##}초 · 재사용 {1:0.##}초','Cast {0:0.##}s · Cooldown {1:0.##}s',2)
(root/'Tools/SkillExpansion/seed.json').write_text(json.dumps(dict(skills=records,strings=strings,jobs=jobs),ensure_ascii=False,indent=2),encoding='utf-8')
print(f'{len(records)} skills, {len(strings)} strings, {len(jobs)} jobs')
